# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=300)),
                ('image_caption', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, max_length=700)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='profile')),
                ('bio', models.TextField(max_length=800)),
            ],
        ),
    ]
