# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed2', '0002_auto_20191014_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
